apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432           # The port PostgreSQL uses
      targetPort: 5432      # The port on the container (should be the same as 'port')
      nodePort: 31543       # NodePort that Kubernetes should expose
      protocol: TCP